
const RecipeActionTypes={
    FETCH_RECIPES_START:'FETCH_RECIPES_START',
    FETCH_RECIPES_SUCCESS:'FETCH_RECIPES_SUCCESS',
    FETCH_RECIPES_FAILURE:'FETCH_RECIPES_FAILURE',
    FETCH_SEARCHED_RECIPES_START:'FETCH_SEARCHED_RECIPES_START',
    FETCH_SEARCHED_RECIPES_SUCCESS:'FETCH_SEARCHED_RECIPES_SUCCESS',
    FETCH_SEARCHED_RECIPES_FAILURE:'FETCH_SEARCHED_RECIPES_FAILURE',
    ADD_RECIPES_START:'ADD_RECIPES_START',
    ADD_RECIPES_SUCCESS:'ADD_RECIPES_SUCCESS',
    ADD_RECIPES_FAILURE:'ADD_RECIPES_FAILURE',
    CLEAR_RECIPES:'CLEAR_RECIPES',
    FETCH_USER_RECIPES_TITLES_START:'FETCH_USER_RECIPES_TITLES_START',
    FETCH_USER_RECIPES_TITLES_SUCCESS:'FETCH_USER_RECIPES_TITLES_SUCCESS',
    FETCH_USER_RECIPES_TITLES_FAILURE:'FETCH_USER_RECIPES_TITLES_FAILURE',
    FETCH_RECIPE_BY_ID_START:'FETCH_RECIPE_BY_ID_START',
    FETCH_RECIPE_BY_ID_SUCCESS:'FETCH_RECIPE_BY_ID_SUCCESS',
    FETCH_RECIPE_BY_ID_FAILURE:'FETCH_RECIPE_BY_ID_FAILURE',
    CLEAR_SEARCH_QUERY:'CLEAR_SEARCH_QUERY',
    DELETE_RECIPE_START:'DELETE_RECIPE_START',
    DELETE_RECIPE_SUCCESS:'DELETE_RECIPE_SUCCESS',
    DELETE_RECIPE_FAILURE:'DELETE_RECIPE_FAILURE',
    CLEAR_CURRENT_RECIPE: 'CLEAR_CURRENT_RECIPE'    
};

export default RecipeActionTypes;