
const RecipeActionTypes={
    FETCH_RECIPES_START:'FETCH_RECIPES_START',
    FETCH_RECIPES_SUCCESS:'FETCH_RECIPES_SUCCESS',
    FETCH_RECIPES_FAILURE:'FETCH_RECIPES_FAILURE',
    ADD_RECIPES_START:'ADD_RECIPES_START',
    ADD_RECIPES_SUCCESS:'ADD_RECIPES_SUCCESS',
    ADD_RECIPES_FAILURE:'ADD_RECIPES_FAILURE'    
};

export default RecipeActionTypes;