const UserActionTypes={
    SET_CURRENT_USER:'SET_CURRENT_USER',
    GOOGLE_SIGN_IN_START:'GOOGLE_SIGN_IN_START',
    GOOGLE_SIGN_IN_SUCCESS:'GOOGLE_SIGN_IN_SUCCESS',
    GOOGLE_SIGN_IN_FAILURE:'GOOGLE_SIGN_IN_FAILURE',
<<<<<<< HEAD
    EMAIL_SIGN_IN_START:'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCCESS:'GOOGLE_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_FAILURE:'GOOGLE_SIGN_IN_FAILURE'

=======
    EMAIL_SIGN_IN_START:'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCCESS:'EMAIL_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_FAILURE:'EMAIL_SIGN_IN_FAILURE',
    SIGN_OUT:'SIGN_OUT',
    CLEAR_USER_ERROR:'CLEAR_USER_ERROR',
    CHECK_USER_SESSION:'CHECK_USER_SESSION'
>>>>>>> tmp
}

export default UserActionTypes;